### ISSUE TITLE
Problem with sticky footer inside the container

### ISSUE THREAD

**Issue by mhaidarhanif** [ariebrainware/glintstodo#1]
I want to make the footer sticky to the bottom with flexbox technique.

**Comment by mhaidarhanif** [comment]
I found a solution here:

https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer

**Comment by ariebrainware** [comment]
masih belum ada jarak antara footer dan section content bang @mhaidarh 
![screenshot from 2018-07-18 14-04-18](https://user-images.githubusercontent.com/26453961/42865361-9f9a956e-8a93-11e8-8004-919e62f57009.png)

https://github.com/ariebrainware/glintstodo/blob/97b227e8e1116f52c81943bcaaf930285961320d/index.html#L15-L61

**Comment by mhaidarhanif** [comment]
Remove the `footer`'s `flex: 1;`

Put the `flex: 1;` to the element before the footer.

**Comment by mhaidarhanif** [comment]
In addition to that, make the footer text in contrast to the background.

Give some padding as well.
