### ISSUE TITLE
How to move add button to rightside textbox?

### ISSUE THREAD

**Issue by ariebrainware** [ariebrainware/glintstodo#2]
https://github.com/ariebrainware/glintstodo/blob/488e7b8cb2f7a9844c726cfc824a0b3812ad48ea/app.html#L15-L24

![issue](https://user-images.githubusercontent.com/26453961/42926182-d255b39a-8b5a-11e8-868a-0e9d6225fdbc.png)

**Comment by michaeltamsil** [comment]
https://lincolnloop.com/blog/smarter-input-groups-flexbox/

for B v.4
https://getbootstrap.com/docs/4.0/components/input-group/#button-addons

**Comment by mhaidarhanif** [comment]
The button should be in the same `form-group` div

**Comment by ariebrainware** [comment]
@mhaidarh I've tried it that way but it's not as expected.
Because textfield height changed

![screenshot from 2018-07-19 14-12-57](https://user-images.githubusercontent.com/26453961/42927184-dd7926d2-8b5d-11e8-9237-3f2ac6906af9.png)

**Comment by michaeltamsil** [comment]
its use flex, TB v,4 too

**Comment by mhaidarhanif** [comment]
If the objective is to "move add button to rightside textbox". Does it already solved?

<img width="570" alt="screen shot 2018-07-19 at 14 18 19" src="https://user-images.githubusercontent.com/235584/42927438-be01bd40-8b5e-11e8-8f9b-00e54a366671.png">

**Comment by mhaidarhanif** [comment]
Keep in mind that `input` and `button` have different behaviors

**Comment by mhaidarhanif** [comment]
Add `height` property to the text box.

<img width="534" alt="screen shot 2018-07-19 at 14 21 18" src="https://user-images.githubusercontent.com/235584/42927559-0c4ade0a-8b5f-11e8-9916-1b8933b7408e.png">

**Comment by ariebrainware** [comment]
Right, i'll try another way

**Comment by ariebrainware** [comment]
[FIXED] thanks @michaeltamsil  @mhaidarh 
![screenshot from 2018-07-19 14-37-29](https://user-images.githubusercontent.com/26453961/42928455-84e13394-8b61-11e8-98eb-1192343ad3f6.png)
